spring.application.name=backend
server.port=8081

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/zodiac_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
